### ISSUE TITLE
Any plans to update for 2020?

### ISSUE THREAD

**Issue by tshrjn** [ankitshah009/all-about-ai-residency#1]
Are there any plans to update the residency list for 2020?

**Comment by ankitshah009** [comment]
Anyone can send pull requests to the GitHub repository. 
https://github.com/dangkhoasdc/awesome-ai-residency - Repository, where some of the links and content was embedded from, is currently updated for 2020. 

Feel free to submit pull requests.

**Comment by ankitshah009** [comment]
Update complete. Collaborators can create pull requests which will be quickly merged.
